debug: false

spring:
  cassandra:
    keyspace-name: my_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      consistency: ONE
